/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=ConfiguredEnv src/worker-configuration.d.ts` (hash: 3c0c123394cef7cbd4ada4f360e46ab3)
interface __BaseEnv_ConfiguredEnv {
	ARCHIVE: R2Bucket;
	DB: D1Database;
	R2_ACCOUNT_ID: string;
	R2_PARENT_ACCESS_KEY_ID: string;
	R2_BUCKET_NAME: string;
	CREDENTIAL_TTL_SECONDS: string;
	UPLOAD_TTL_SECONDS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ConfiguredEnv {}
}
interface ConfiguredEnv extends __BaseEnv_ConfiguredEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ACCOUNT_ID" | "R2_PARENT_ACCESS_KEY_ID" | "R2_BUCKET_NAME" | "CREDENTIAL_TTL_SECONDS" | "UPLOAD_TTL_SECONDS">> {}
}
